config/routes.rb
Rails.application.routes.draw do
  
  resources :revoews
  devise_for :users
  resources :restaurants do
    resources :reviews, except: [:show, :index]
  end
  get 'pages/about'
  get 'pages/contact'
  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/revoew.rb
class Revoew < ApplicationRecord
end

app/controllers/revoews_controller.rb
class RevoewsController < ApplicationController
  before_action :set_revoew, only: [:show, :edit, :update, :destroy]

  # GET /revoews
  # GET /revoews.json
  def index
    @revoews = Revoew.all
  end

  # GET /revoews/1
  # GET /revoews/1.json
  def show
  end

  # GET /revoews/new
  def new
    @revoew = Revoew.new
  end

  # GET /revoews/1/edit
  def edit
  end

  # POST /revoews
  # POST /revoews.json
  def create
    @revoew = Revoew.new(revoew_params)

    respond_to do |format|
      if @revoew.save
        format.html { redirect_to @revoew, notice: 'Revoew was successfully created.' }
        format.json { render :show, status: :created, location: @revoew }
      else
        format.html { render :new }
        format.json { render json: @revoew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /revoews/1
  # PATCH/PUT /revoews/1.json
  def update
    respond_to do |format|
      if @revoew.update(revoew_params)
        format.html { redirect_to @revoew, notice: 'Revoew was successfully updated.' }
        format.json { render :show, status: :ok, location: @revoew }
      else
        format.html { render :edit }
        format.json { render json: @revoew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revoews/1
  # DELETE /revoews/1.json
  def destroy
    @revoew.destroy
    respond_to do |format|
      format.html { redirect_to revoews_url, notice: 'Revoew was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_revoew
      @revoew = Revoew.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def revoew_params
      params.require(:revoew).permit(:rating, :comment)
    end
end

app/helpers/revoews_helper.rb
module RevoewsHelper
end

app/views/revoews/_form.html.erb
<%= form_with(model: revoew, local: true) do |form| %>
  <% if revoew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(revoew.errors.count, "error") %> prohibited this revoew from being saved:</h2>

      <ul>
      <% revoew.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/revoews/edit.html.erb
<h1>Editing Revoew</h1>

<%= render 'form', revoew: @revoew %>

<%= link_to 'Show', @revoew %> |
<%= link_to 'Back', revoews_path %>

app/views/revoews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Revoews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @revoews.each do |revoew| %>
      <tr>
        <td><%= revoew.rating %></td>
        <td><%= revoew.comment %></td>
        <td><%= link_to 'Show', revoew %></td>
        <td><%= link_to 'Edit', edit_revoew_path(revoew) %></td>
        <td><%= link_to 'Destroy', revoew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Revoew', new_revoew_path %>

app/views/revoews/new.html.erb
<h1>New Revoew</h1>

<%= render 'form', revoew: @revoew %>

<%= link_to 'Back', revoews_path %>

app/views/revoews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @revoew.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @revoew.comment %>
</p>

<%= link_to 'Edit', edit_revoew_path(@revoew) %> |
<%= link_to 'Back', revoews_path %>