config/routes.rb
Rails.application.routes.draw do
  
  resources :revoews
  devise_for :users
  resources :restaurants do
    resources :reviews, except: [:show, :index]
  end
  get 'pages/about'
  get 'pages/contact'
  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
     mount_uploader :image, ImageUploader

     has_many :reviews
     
     validates :name, :adress, :phone, :website, :image, presence: true
     validates :phone, format: { with: /\d{3}/,
    message: "must be in the format 000 000 000" }
    validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
    message: "must start with http:// or https//:" }
    validates :adress, format: { with: /\A\d+[^,]+,[^,]+, [A-Z]{2} \d{5}\z/,
    message: "must be in the formate 350 fifth avenue, New York, NT 10015" }
end
 

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, except: [:index, :show]
  

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @reviews = Review.where(restaurant_id: @restaurant.id).order(created_at: :desc)
    if @reviews.blank?
        @avg_rating = 0
      else
        @avg_rating = @avg_rating = @reviews.average(:rating).round(2)
      end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end
    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "sorry, only admin can do that"
        end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :adress, :phone, :website, :image)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true, :html =>{multipart: true}) do |form| %>
<% if restaurant.errors.any? %>
<div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h4>

  <ul>
    <% restaurant.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class:"form-control", placeholder: "Boulangerie Saker" %>
</div>

<div class="field form-group">
  <%= form.label :adress %>
  <%= form.text_field :adress, class:"form-control", placeholder: "malangue Beedi" %>
</div>

<div class="field form-group">
  <%= form.label :phone %>
  <%= form.text_field :phone, class:"form-control", placeholder: "675577785" %>
</div>

<div class="field form-group">
  <%= form.label :website %>
  <%= form.text_field :website, class:"form-control" , placeholder: "https://www.google.com"%>
</div>

<div class="field form-group">
  <%= form.label :image %>
  <%= form.file_field :image, class:"form-control" %>
</div>

<div class="actions">
  <%= form.submit class:"btn btn-primary" %>
</div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant, class:"btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class:"btn btn-link" %>

app/views/restaurants/index.html.erb
<div class="jumbotron">
<h2>Get all restaurant reviews on yelpdemo</h2>
<h3>Make your community enjoy the best meals from<br>
their favourute restaurant.
</h3>
</div>
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Adress</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
      <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
       <td> <%= link_to  restaurant.name, restaurant %></td>
        <td><%= restaurant.adress %></td>
        <td><%= restaurant.phone %></td>
        <td> <%= link_to  restaurant.website, restaurant.website %> </td>
       <% if user_signed_in? && current_user.admin? %>
         <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class:"btn btn-link" %></td>
         <td>
           <%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-link" %>
         </td>
       <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Restaurant', new_restaurant_path %>
<% end %>

<%= image_tag  "footer_cityscape.png" %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path, class:"btn btn-link" %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-3">
    <%= image_tag @restaurant.image_url %>
    <h2>

      <%= @restaurant.name %>
    </h2>

    <div class="star-rating" data-score=<%= @avg_rating %>></div>
    <p><%= "#{@reviews.length} reviews" %></p>
    <p>
      <strong>Adress:</strong>
      <%= @restaurant.adress %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @restaurant.phone %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= link_to @restaurant.website , @restaurant.website %>
    </p>

    <%= link_to"Write Review" , new_restaurant_review_path(@restaurant), class:"btn re btn-primary" %>
    <br>
   <div style='width: 300px;'>
     <div id="map" style='width: 300px; height: 300px;'></div>
   </div>
  </div>

  <div class="col-md-9">
    <% if @reviews.blank? %>
    <h3>No reviews yrt. Be the first to wite one</h3>
    <% else %>
    <table class="table">
      <thead>
        <tr>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review| %>
        <tr>
          <td>
            <h4>
              <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}."%>
            </h4>
            <p><%= review.created_at.strftime("%-m/%-d/%y") %></p>
          </td>
          <td>
            <div class="star-rating" data-score=<%=review.rating %>></div>
            <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
           <% if user_signed_in? %>
              <% if (review.user == current_user) || (current_user.admin?) %>
                  <%= link_to  "Edit", edit_restaurant_review_path(@restaurant, review) %>
                  <%= link_to  "Delete", restaurant_review_path(@restaurant, review), method: :delete%>             
              <% end %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

<%= link_to 'Edit',edit_restaurant_path(@restaurant) , class:" btnbtn-link" %> |
<%= link_to 'Back', restaurants_path, class:" btn btn-link" %>

<script>

  //js map code
handler = Gmaps.build('Google');
handler.buildMap({ provider: {
  disableDefaultUI: true,
  
}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 5.480400,
      "lng": 10.444775,
      "picture": {
        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "HOME!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
}); 
//js star rating
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function () {
      return $(this).attr('data-score');
    }
  });
</script>