config/routes.rb
Rails.application.routes.draw do
  
  resources :revoews
  devise_for :users
  resources :restaurants do
    resources :reviews, except: [:show, :index]
  end
  get 'pages/about'
  get 'pages/contact'
  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<p>Copyright Stec</p>

app/views/layouts/_js_depedencies.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyBQjyS2F_jApSSrAD2nVhtgxhomwuwF6SM"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script
  src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js'
  type='text/javascript'>
</script> <!-- only if you need custom infoboxes -->

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to  "Yelpdemo", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to  "About", pages_about_path, class:"nav-link" %>
      </li>
       <li class="nav-item">
       <%= link_to  "Contact", pages_contact_path, class:"nav-link" %>
      </li>
    </ul>
    <form class="form-inline  mr-auto">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      
    </form>
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
       <li class="nav-item">
       <%= link_to  "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>
      </li>
       <li class="nav-item">
       <%= link_to  "Edit profile",  edit_user_registration_path, class:"nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
      <%= link_to  "Sign up", new_user_registration_path, class:"nav-link" %>
      </li>
       <li class="nav-item">
       <%= link_to  "Sign in",  new_user_session_path, class:"nav-link" %>
      </li>
      
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelpdemo</title>  

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <script src="//maps.google.com/maps/api/js?key=AIzaSyBQjyS2F_jApSSrAD2nVhtgxhomwuwF6SM"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script
      src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js'
      type='text/javascript'>
    </script
    
  </head>

  <body>
  <!--render nav bar-->
<%= render 'layouts/navbar'%>
<div class="container-fluid">
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/footer'%>
    </div>
  </body>
</html>